### ISSUE TITLE
Is there an L2 implementation for cloudfront.CfnCloudFrontOriginAccessIdentity

### ISSUE THREAD

**Issue by DavidChristiansen** [DavidChristiansen/aws-modern-application-workshop#29]
https://github.com/DavidChristiansen/aws-modern-application-workshop/blob/cdk-typescript/module-1/cdk/lib/WebApplicationStack.ts#L24

**Comment by skinny85** [comment]
There is not :( see integration test: https://github.com/awslabs/aws-cdk/blob/d0e19d50f5fc1459cea66b309aaa9fe18a3d9618/packages/%40aws-cdk/aws-cloudfront/test/integ.cloudfront-s3.ts#L10
